const MAX_WF = 2048;

export const state = {
  audioCtx: null,
  source: null,
  analyser: null,
  audioBuffer: null,
  isPlaying: false,
  isRecording: false,
  smoothedPeriod: 0,
  freqBuf: null,
  timeBuf: null,
  filtBuf: null,
  bassEnergy: 0,
  smoothedBass: 0,
  bassHit: false,
  prevBassSpectrum: null,
  smoothedFlux: 0,
  playOffset: 0,
  playStartCtxTime: 0,
  displayW: 0,
  displayH: 0,
  scopeDirty: true,
  wfYs: new Float32Array(MAX_WF),
  wfCount: 0,
  wfLeft: 0,
  wfRight: 0,
  wfActive: false,
  overviewPeaks: null,
  overviewDuration: 0,
  edgeWrap: true,
  activeHue: 135,
  gradient: false,
  gradColor1: '#00ff41',
  gradColor2: '#4488ff',
  gradHue1: 135,
  gradHue2: 218,
  mobilePreview: false,
  cropX: 0,
  cropW: 0,
  recVertical: false,
  iconSrc: 'assets/shisoflower.png',
  audioFileName: 'flowerscope',
  recCanvas: null,
  recCtx: null,
  flowers: [],
};
